# Generated by Django 4.2.7 on 2026-07-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plazo_meses', models.IntegerField()),
                ('comercial', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
