# Generated by Django 4.2.7 on 2026-07-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_credito_delete_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
